# Generated by Django 4.2.3 on 2023-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0003_remove_job_category_remove_job_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Senior Level', 'Senior Level'), ('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Full-Time', 'Full-Time')], default=0, max_length=50),
        ),
    ]
