# Generated by Django 4.2.3 on 2023-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0007_alter_job_company_alter_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Senior Level', 'Senior Level'), ('Mid Level', 'Mid Level')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Temporary', 'Temporary'), ('Contract', 'Contract'), ('Part-Time', 'Part-Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
