# Generated by Django 4.2.3 on 2023-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_instructions',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Senior Level', 'Senior Level'), ('Mid Level', 'Mid Level'), ('Entry Level', 'Entry Level')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=0),
        ),
    ]
