# Generated by Django 4.2.3 on 2023-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0002_job_application_instructions_job_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Part-Time', 'Part-Time'), ('Temporary', 'Temporary'), ('Full-Time', 'Full-Time')], default=0, max_length=50),
        ),
    ]
