# Generated by Django 4.2.3 on 2023-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0006_remove_job_application_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Mid Level', 'Mid Level'), ('Entry Level', 'Entry Level'), ('Senior Level', 'Senior Level')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Temporary', 'Temporary'), ('Contract', 'Contract')], default=0, max_length=50),
        ),
    ]
